name: "EnOcean MQTT (net-dev)"
description: "EnOcean to MQTT bridge for Home Assistant w/ tcp support"
url: "https://github.com/tostmann/HA_enoceanmqtt-addon"
version: "0.1.28-5"
slug: "ha_enoceanmqtt_net_dev"
stage: "experimental"
init: false
uart: true
hassio_api: true
homeassistant_api: true
startup: "application"
services:
  - "mqtt:need"
map:
  - "config:rw"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  device_file: ""
  mapping_file: ""
  eep_file: ""
  log_file: "/config/enoceanmqtt.log"
  enocean_port: ""
  debug: false
  log_packets: false
  use_dev_name_in_entity: false
  mqtt_broker: {}
  mqtt_discovery_prefix: "homeassistant"
  mqtt_prefix: "enoceanmqtt"
  mqtt_client_id: "enocean_gateway"
  mqtt_keepalive: 60
schema:
  device_file: "str"
  mapping_file: "str?"
  eep_file: "str?"
  log_file: "str?"
  enocean_port: "str"
  debug: "bool?"
  log_packets: "bool?"
  use_dev_name_in_entity: "bool?"
  mqtt_broker:
    host: "str?"
    port: "str?"
    user: "str?"
    pwd: "password?"
  mqtt_discovery_prefix: "str"
  mqtt_prefix: "str"
  mqtt_client_id: "str"
  mqtt_keepalive: "int"
